name: mobile_loading
description: "A new Flutter project."
publish_to: 'none'
version: 0.3.9+15
environment:
  sdk: ^3.9.2

dependencies:
  back_button_interceptor: ^8.0.4
  firebase_analytics: ^12.4.3
  firebase_core: ^4.11.0
  firebase_remote_config: ^6.5.3
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/app_icon/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/app_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#121212"
  image: "assets/app_icon/app_logo.png"
  android: true
  ios: true
